name: Deploy Quartz site to GitHub Pages
 
on:
  push:
    branches:
      - master
 
permissions:
  contents: read
  pages: write
  id-token: write
 
concurrency:
  group: "pages"
  cancel-in-progress: false
 
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for git info
          submodules: 'recursive' # Option to checkout submodules
      - name: Setup Node.js
        uses: actions/setup-node@v4
      - name: Copy files to Quartz content directory
        run: |
          cp -r docs/* sites/docs/
      - name: Install Dependencies
        run: | 
          cd sites/docs
          npm ci
      - name: Build Quartz
        run: |
          cd sites/docs
          npm run quartz build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: sites/docs/public
 
  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4